name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a dummy commit
        run: |
          echo "Update: $(date)" >> update.log
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add update.log
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push
